### ISSUE TITLE
Can't find obs page on refresh

### ISSUE THREAD

**Issue by sbbu** [ternandsparrow/wild-orchid-watch-pwa#100]
Env
Commit fb482c0
Chrome 102 on Linux

Steps
1. launch app and login
2. open the details page for an observation (tap on it)
3. refresh the page

Expected:
The page refreshes and loads normally. This currently works on https://beta.app.wildorchidwatch.org/

Actual:
The observation cannot be found and the page displays a 'not found' error to the user.
![image](https://user-images.githubusercontent.com/102282561/172975494-3c666120-0480-4079-978f-3945fa1a533e.png)
![image](https://user-images.githubusercontent.com/102282561/172975596-fdaf6d73-0f14-4549-8133-4e2bd14f30bf.png)

**Comment by tomsaleeba** [comment]
This should be fixed by [line 233 in router.js](https://github.com/ternandsparrow/wild-orchid-watch-pwa/pull/101/files#diff-d7f41ba1aa74f41ef4b0c2337abe593d08092ffae6528a8aa2db712afeee0b66R233) that I just merged. The problem, as hinted by the warning, is that it can't find the ID. This is because I used `===` so the string type of the param won't match the number type in the record. The fix was the cast the string to a number.

The error after that is a red herring. It comes from OnsenUI and it happens everytime you directly load the ObsDetail page. Just go the page and reload and you'll see if everytime. I did look into it ages ago, but couldn't fix it then, and it doesn't break anything so :see_no_evil: .

Can you re-test and see if my PR fixes this bug? If it does, the bug can be closed :muscle:

**Comment by sbbu** [comment]
I've tested and verified that the bug is fixed 👍
